"""
Code Interpreter for Code-as-Reasoning.

This module provides a secure sandboxed environment for executing code
generated by the language model. Instead of hallucinating computation,
the model can write and execute code to verify facts and perform calculations.

Architecture:
    1. Code Parser: Extract code blocks from model output
    2. Sandbox: Secure execution environment
    3. Result Formatter: Format execution results as observations

Security Considerations:
    - Resource limits (CPU time, memory)
    - Restricted imports (no os, sys, subprocess, etc.)
    - No file system access
    - No network access

Execution Modes:
    1. RestrictedPython: In-process with AST restrictions
    2. Subprocess: Isolated process with timeout
    3. Docker: Full container isolation (most secure)
"""

import ast
import re
import sys
import time
import traceback
import signal
import multiprocessing
from io import StringIO
from dataclasses import dataclass
from typing import Optional, List, Dict, Any, Tuple
from contextlib import contextmanager, redirect_stdout, redirect_stderr
from functools import wraps
import builtins


@dataclass
class CodeInterpreterConfig:
    """Configuration for code interpreter."""
    max_execution_time: float = 30.0
    max_memory_mb: int = 512
    max_output_length: int = 10000
    sandbox_type: str = "restricted"  # "restricted", "subprocess", "docker"
    allowed_modules: List[str] = None
    code_block_pattern: str = r"```(?:python)?\n(.*?)```"
    include_traceback: bool = True
    max_traceback_lines: int = 10

    def __post_init__(self):
        if self.allowed_modules is None:
            self.allowed_modules = [
                "math", "statistics", "collections", "itertools", "functools",
                "re", "json", "datetime", "random", "string", "decimal",
                "fractions", "heapq", "bisect", "copy", "operator", "typing",
                "dataclasses", "enum", "abc"
            ]


@dataclass
class ExecutionResult:
    """Result of code execution."""
    success: bool
    output: str
    error: Optional[str] = None
    return_value: Any = None
    execution_time: float = 0.0
    memory_used: int = 0

    def to_observation(self) -> str:
        """Format as observation for model context."""
        if self.success:
            obs = f"[Execution successful in {self.execution_time:.2f}s]\n"
            if self.output:
                obs += f"Output:\n{self.output}\n"
            if self.return_value is not None:
                obs += f"Return value: {self.return_value}\n"
            return obs
        else:
            return f"[Execution failed]\nError: {self.error}\n"


class CodeParser:
    """Parse code blocks from model output."""

    def __init__(self, config: CodeInterpreterConfig):
        self.config = config
        self.pattern = re.compile(config.code_block_pattern, re.DOTALL)

    def extract_code_blocks(self, text: str) -> List[str]:
        """
        Extract all code blocks from text.

        Args:
            text: Model output potentially containing code blocks

        Returns:
            List of code strings
        """
        matches = self.pattern.findall(text)
        return [m.strip() for m in matches if m.strip()]

    def extract_last_code_block(self, text: str) -> Optional[str]:
        """Extract the last code block from text."""
        blocks = self.extract_code_blocks(text)
        return blocks[-1] if blocks else None

    def has_code_block(self, text: str) -> bool:
        """Check if text contains any code blocks."""
        return bool(self.pattern.search(text))


class SecurityChecker:
    """
    AST-based security checker for Python code.

    Validates code doesn't use dangerous operations before execution.
    """

    # Dangerous built-ins to block
    DANGEROUS_BUILTINS = {
        'eval', 'exec', 'compile', 'open', 'input', '__import__',
        'globals', 'locals', 'vars', 'dir', 'getattr', 'setattr',
        'delattr', 'hasattr', 'type', 'isinstance', 'issubclass',
        'callable', 'classmethod', 'staticmethod', 'property',
        'super', 'object', 'memoryview', 'breakpoint'
    }

    # Dangerous modules to block
    DANGEROUS_MODULES = {
        'os', 'sys', 'subprocess', 'shutil', 'pathlib', 'glob',
        'socket', 'http', 'urllib', 'requests', 'ftplib', 'smtplib',
        'pickle', 'shelve', 'marshal', 'dbm', 'sqlite3',
        'multiprocessing', 'threading', 'concurrent', 'asyncio',
        'ctypes', 'cffi', 'importlib', 'pkgutil', 'inspect',
        'code', 'codeop', 'dis', 'gc', 'tracemalloc', 'resource',
        'signal', 'pty', 'tty', 'termios', 'fcntl',
    }

    # Dangerous AST node types
    DANGEROUS_NODES = {
        ast.AsyncFunctionDef, ast.AsyncFor, ast.AsyncWith,
        ast.Await, ast.Yield, ast.YieldFrom,
    }

    def __init__(self, allowed_modules: List[str]):
        self.allowed_modules = set(allowed_modules)

    def check(self, code: str) -> Tuple[bool, Optional[str]]:
        """
        Check if code is safe to execute.

        Args:
            code: Python code string

        Returns:
            (is_safe, error_message)
        """
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"

        for node in ast.walk(tree):
            # Check for dangerous node types
            if type(node) in self.DANGEROUS_NODES:
                return False, f"Async operations not allowed: {type(node).__name__}"

            # Check imports
            if isinstance(node, ast.Import):
                for alias in node.names:
                    module = alias.name.split('.')[0]
                    if module in self.DANGEROUS_MODULES:
                        return False, f"Import of '{module}' not allowed"
                    if module not in self.allowed_modules:
                        return False, f"Module '{module}' not in allowed list"

            if isinstance(node, ast.ImportFrom):
                if node.module:
                    module = node.module.split('.')[0]
                    if module in self.DANGEROUS_MODULES:
                        return False, f"Import from '{module}' not allowed"
                    if module not in self.allowed_modules:
                        return False, f"Module '{module}' not in allowed list"

            # Check for dangerous built-in calls
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    if node.func.id in self.DANGEROUS_BUILTINS:
                        return False, f"Built-in '{node.func.id}' not allowed"

            # Check for attribute access to dunder methods
            if isinstance(node, ast.Attribute):
                if node.attr.startswith('__') and node.attr.endswith('__'):
                    if node.attr not in ('__init__', '__str__', '__repr__', '__len__',
                                         '__iter__', '__next__', '__getitem__', '__setitem__',
                                         '__contains__', '__add__', '__sub__', '__mul__',
                                         '__truediv__', '__eq__', '__lt__', '__gt__',
                                         '__le__', '__ge__', '__hash__', '__bool__'):
                        return False, f"Access to '{node.attr}' not allowed"

        return True, None


class RestrictedExecutor:
    """
    Execute Python code in a restricted environment.

    Uses a custom namespace with safe built-ins only.
    """

    def __init__(self, config: CodeInterpreterConfig):
        self.config = config
        self.security = SecurityChecker(config.allowed_modules)

    def _create_safe_builtins(self) -> Dict[str, Any]:
        """Create a dictionary of safe built-in functions."""
        safe_builtins = {}

        # Safe built-ins to include
        SAFE_NAMES = [
            'abs', 'all', 'any', 'ascii', 'bin', 'bool', 'bytearray', 'bytes',
            'chr', 'complex', 'dict', 'divmod', 'enumerate', 'filter', 'float',
            'format', 'frozenset', 'hash', 'hex', 'int', 'iter', 'len', 'list',
            'map', 'max', 'min', 'next', 'oct', 'ord', 'pow', 'print', 'range',
            'repr', 'reversed', 'round', 'set', 'slice', 'sorted', 'str', 'sum',
            'tuple', 'zip', 'True', 'False', 'None'
        ]

        for name in SAFE_NAMES:
            if hasattr(builtins, name):
                safe_builtins[name] = getattr(builtins, name)

        # Add safe exceptions
        safe_exceptions = [
            'Exception', 'BaseException', 'ValueError', 'TypeError', 'KeyError',
            'IndexError', 'AttributeError', 'RuntimeError', 'StopIteration',
            'ZeroDivisionError', 'OverflowError', 'ArithmeticError'
        ]
        for exc in safe_exceptions:
            if hasattr(builtins, exc):
                safe_builtins[exc] = getattr(builtins, exc)

        return safe_builtins

    def _create_safe_namespace(self) -> Dict[str, Any]:
        """Create a safe execution namespace."""
        namespace = {
            '__builtins__': self._create_safe_builtins(),
            '__name__': '__main__',
        }

        # Import allowed modules
        for module_name in self.config.allowed_modules:
            try:
                module = __import__(module_name)
                namespace[module_name] = module
            except ImportError:
                pass

        return namespace

    def execute(self, code: str) -> ExecutionResult:
        """
        Execute code in restricted environment.

        Args:
            code: Python code to execute

        Returns:
            ExecutionResult with output and status
        """
        # Security check
        is_safe, error = self.security.check(code)
        if not is_safe:
            return ExecutionResult(
                success=False,
                output="",
                error=f"Security violation: {error}",
            )

        # Prepare namespace
        namespace = self._create_safe_namespace()

        # Capture output
        stdout_capture = StringIO()
        stderr_capture = StringIO()

        start_time = time.time()
        return_value = None
        error_msg = None

        try:
            # Parse and compile
            tree = ast.parse(code)

            # If last statement is expression, capture its value
            if tree.body and isinstance(tree.body[-1], ast.Expr):
                # Wrap last expression in assignment to capture result
                last_expr = tree.body.pop()
                assign = ast.Assign(
                    targets=[ast.Name(id='__result__', ctx=ast.Store())],
                    value=last_expr.value
                )
                assign.lineno = last_expr.lineno
                assign.col_offset = last_expr.col_offset
                tree.body.append(assign)

            compiled = compile(tree, '<sandbox>', 'exec')

            # Execute with timeout
            with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
                exec(compiled, namespace)

            # Get return value
            return_value = namespace.get('__result__')

        except Exception as e:
            error_msg = self._format_error(e)

        execution_time = time.time() - start_time

        # Get output
        output = stdout_capture.getvalue()
        stderr = stderr_capture.getvalue()

        if stderr and not error_msg:
            error_msg = stderr

        # Truncate output
        if len(output) > self.config.max_output_length:
            output = output[:self.config.max_output_length] + "\n... (output truncated)"

        return ExecutionResult(
            success=error_msg is None,
            output=output,
            error=error_msg,
            return_value=return_value,
            execution_time=execution_time,
        )

    def _format_error(self, e: Exception) -> str:
        """Format exception for output."""
        if self.config.include_traceback:
            tb_lines = traceback.format_exception(type(e), e, e.__traceback__)
            # Limit traceback length
            if len(tb_lines) > self.config.max_traceback_lines:
                tb_lines = tb_lines[:self.config.max_traceback_lines] + ["... (traceback truncated)\n"]
            return "".join(tb_lines)
        return f"{type(e).__name__}: {e}"


def _subprocess_worker(code: str, result_queue: multiprocessing.Queue):
    """Worker function for subprocess execution."""
    try:
        # Create minimal namespace
        namespace = {'__builtins__': __builtins__}

        # Capture output
        stdout_capture = StringIO()
        stderr_capture = StringIO()

        with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
            exec(code, namespace)

        result_queue.put({
            'success': True,
            'output': stdout_capture.getvalue(),
            'error': stderr_capture.getvalue() or None,
        })
    except Exception as e:
        result_queue.put({
            'success': False,
            'output': '',
            'error': f"{type(e).__name__}: {e}",
        })


class SubprocessExecutor:
    """
    Execute code in a separate process for isolation.

    Provides better isolation than RestrictedExecutor but
    higher overhead.
    """

    def __init__(self, config: CodeInterpreterConfig):
        self.config = config
        self.security = SecurityChecker(config.allowed_modules)

    def execute(self, code: str) -> ExecutionResult:
        """Execute code in subprocess with timeout."""
        # Security check first
        is_safe, error = self.security.check(code)
        if not is_safe:
            return ExecutionResult(
                success=False,
                output="",
                error=f"Security violation: {error}",
            )

        start_time = time.time()

        # Create result queue
        result_queue = multiprocessing.Queue()

        # Start worker process
        process = multiprocessing.Process(
            target=_subprocess_worker,
            args=(code, result_queue)
        )
        process.start()

        # Wait with timeout
        process.join(timeout=self.config.max_execution_time)

        execution_time = time.time() - start_time

        if process.is_alive():
            # Timeout - kill process
            process.terminate()
            process.join(timeout=1)
            if process.is_alive():
                process.kill()

            return ExecutionResult(
                success=False,
                output="",
                error=f"Execution timed out after {self.config.max_execution_time}s",
                execution_time=execution_time,
            )

        # Get result
        try:
            result = result_queue.get_nowait()
            return ExecutionResult(
                success=result['success'],
                output=result['output'][:self.config.max_output_length],
                error=result['error'],
                execution_time=execution_time,
            )
        except Exception:
            return ExecutionResult(
                success=False,
                output="",
                error="Failed to get result from subprocess",
                execution_time=execution_time,
            )


class CodeInterpreter:
    """
    Main interface for code execution.

    Parses code from model output, executes it safely,
    and formats results as observations.
    """

    def __init__(self, config: CodeInterpreterConfig = None):
        """
        Initialize code interpreter.

        Args:
            config: Configuration options
        """
        self.config = config or CodeInterpreterConfig()
        self.parser = CodeParser(self.config)

        # Select executor based on config
        if self.config.sandbox_type == "subprocess":
            self.executor = SubprocessExecutor(self.config)
        else:
            self.executor = RestrictedExecutor(self.config)

    def execute(self, code: str) -> ExecutionResult:
        """
        Execute a code string.

        Args:
            code: Python code to execute

        Returns:
            ExecutionResult with output and status
        """
        return self.executor.execute(code)

    def execute_from_text(self, text: str) -> Optional[ExecutionResult]:
        """
        Extract and execute code from model output.

        Args:
            text: Model output potentially containing code blocks

        Returns:
            ExecutionResult if code was found and executed, None otherwise
        """
        code = self.parser.extract_last_code_block(text)
        if code is None:
            return None
        return self.execute(code)

    def execute_all_from_text(self, text: str) -> List[ExecutionResult]:
        """
        Execute all code blocks from model output.

        Args:
            text: Model output with multiple code blocks

        Returns:
            List of ExecutionResults
        """
        code_blocks = self.parser.extract_code_blocks(text)
        return [self.execute(code) for code in code_blocks]

    def should_execute(self, text: str) -> bool:
        """Check if text contains code that should be executed."""
        return self.parser.has_code_block(text)

    def format_observation(self, result: ExecutionResult) -> str:
        """Format execution result as observation for model context."""
        return result.to_observation()


class ReActCodeInterpreter:
    """
    Code interpreter with ReAct-style observation formatting.

    Formats execution results to be fed back into the model's
    context for iterative reasoning.
    """

    OBSERVATION_TEMPLATE = """
Observation: {observation}
Thought: Let me analyze this result and continue reasoning...
"""

    def __init__(self, config: CodeInterpreterConfig = None):
        self.interpreter = CodeInterpreter(config)

    def process_and_observe(self, model_output: str) -> Tuple[bool, str]:
        """
        Process model output, execute code if present, return observation.

        Args:
            model_output: The model's generated text

        Returns:
            (has_code, updated_context): Whether code was executed and
            the text to append to context
        """
        if not self.interpreter.should_execute(model_output):
            return False, ""

        result = self.interpreter.execute_from_text(model_output)
        if result is None:
            return False, ""

        observation = result.to_observation()
        return True, self.OBSERVATION_TEMPLATE.format(observation=observation)

    def run_agent_loop(
        self,
        model: Any,
        tokenizer: Any,
        initial_prompt: str,
        max_iterations: int = 5,
    ) -> str:
        """
        Run a ReAct-style agent loop with code execution.

        Args:
            model: The language model
            tokenizer: Tokenizer for the model
            initial_prompt: Starting prompt/question
            max_iterations: Maximum reasoning iterations

        Returns:
            Final context with all reasoning and observations
        """
        context = initial_prompt

        for _ in range(max_iterations):
            # Generate next step
            input_ids = tokenizer.encode(context, return_tensors="pt")
            input_ids = input_ids.to(next(model.parameters()).device)

            with torch.no_grad():
                outputs = model.generate(
                    input_ids,
                    max_new_tokens=500,
                    temperature=0.7,
                    do_sample=True,
                )

            generated = tokenizer.decode(
                outputs[0][input_ids.shape[1]:],
                skip_special_tokens=True,
            )

            context += generated

            # Check for code and execute
            has_code, observation = self.process_and_observe(generated)

            if has_code:
                context += observation
            else:
                # No code = reasoning complete
                break

        return context


# Utility to make CodeInterpreter work with torch
import torch


class TorchCodeInterpreter(CodeInterpreter):
    """Code interpreter with PyTorch integration."""

    def __init__(self, config: CodeInterpreterConfig = None):
        if config is None:
            config = CodeInterpreterConfig()

        # Add numpy and torch to allowed modules for math operations
        config.allowed_modules = list(config.allowed_modules) + ['numpy']

        super().__init__(config)

    def execute_with_tensor_support(
        self,
        code: str,
        tensors: Dict[str, torch.Tensor] = None,
    ) -> ExecutionResult:
        """
        Execute code with tensor variables available.

        Args:
            code: Python code
            tensors: Dictionary of tensor variables to make available

        Returns:
            ExecutionResult
        """
        # Add tensor assignments to code
        if tensors:
            tensor_setup = []
            for name, tensor in tensors.items():
                # Convert to list for safe transmission
                tensor_setup.append(f"{name} = {tensor.tolist()}")
            setup_code = "\n".join(tensor_setup) + "\n"
            code = setup_code + code

        return self.execute(code)
